<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);InlineComponent</InterceptorsNamespaces>
        <EnableAutoRows>true</EnableAutoRows>
        <EnableAutoTextDisplay>true</EnableAutoTextDisplay>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="EnableAutoRows" />
        <CompilerVisibleProperty Include="EnableAutoTextDisplay" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\ComponentDesigner.Core\ComponentDesigner.Core.csproj" />
      <ProjectReference Include="..\src\ComponentDesigner.Graph\ComponentDesigner.Graph.csproj" />
      <ProjectReference Include="..\src\ComponentDesigner.Parser\ComponentDesigner.Parser.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Discord.Net.Core" Version="3.18.0" />
    </ItemGroup>
    
<!--    <ItemGroup>-->
<!--        <ProjectReference Include="..\src\Discord.Net.ComponentDesigner.Generator\Discord.Net.ComponentDesigner.Generator.csproj" OutputItemType="Analyzer" />-->
<!--        <ProjectReference Include="..\src\Discord.Net.ComponentDesigner.Parser\Discord.Net.ComponentDesigner.Parser.csproj" OutputItemType="Analyzer"/>-->
<!--        <ProjectReference Include="..\src\Discord.Net.ComponentDesigner\Discord.Net.ComponentDesigner.csproj"/>-->
<!--    </ItemGroup>-->

</Project>
