<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>cx</string>
    <key>scopeName</key>
    <string>source.cx</string>
    <key>fileTypes</key>
    <array>
      <string>cx</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#element</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>element</key>
      <dict>
        <key>begin</key>
        <string>(&lt;/?)\s*([_a-zA-Z][_\-.a-zA-Z0-9]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.open.cx</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.cx</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\s*\/?&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.close.cx</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attributes</string>
          </dict>
        </array>
      </dict>
      <key>attributes</key>
      <dict>
        <key>begin</key>
        <string>\s+</string>
        <key>end</key>
        <string>(?=/?&gt;)</string>
        <key>name</key>
        <string>meta.tag.attributes.cx</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attribute</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#element-value</string>
          </dict>
        </array>
      </dict>
      <key>element-value</key>
      <dict>
        <key>begin</key>
        <string>(\()</string>
        <key>end</key>
        <string>(\))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.paren.open.cx</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.paren.close.cx</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#element</string>
          </dict>
        </array>
      </dict>
      <key>attribute</key>
      <dict>
        <key>match</key>
        <string>([_a-zA-Z][_\-.a-zA-Z0-9]*)(?=[=\s]|/?&gt;|/\*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.cx</string>
          </dict>
        </dict>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#single-quoted-string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#double-quoted-string</string>
          </dict>
        </array>
      </dict>
      <key>single-quoted-string</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.cx</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.cx</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.cx</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-escapes</string>
          </dict>
        </array>
      </dict>
      <key>double-quoted-string</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.cx</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.cx</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.cx</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-escapes</string>
          </dict>
        </array>
      </dict>
      <key>string-escapes</key>
      <dict>
        <key>match</key>
        <string>\\(x\h{2}|u\h{4}|u\{\h+}|[012][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)</string>
        <key>name</key>
        <string>constant.character.escape.cx</string>
      </dict>
    </dict>
  </dict>
</plist>