<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="samples\incr-1.txt" />
      <EmbeddedResource Include="samples\incr-1.txt" />
      <None Remove="samples\incr-2.txt" />
      <EmbeddedResource Include="samples\incr-2.txt" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\ComponentDesigner.Parser\ComponentDesigner.Parser.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>

</Project>
